version: '3'

services:

  database:
    env_file:
      - database/.env
    container_name: database
    build:
      context: .
      dockerfile: database/Dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  backend:
    env_file:
      - backend/.env
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_PORT=$POSTGRES_PORT
    depends_on: 
      - database
    tty: true
    volumes:
      - ./backend:/go/app

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on: 
      - backend
    tty: true
    volumes:
      - ./frontend:/app

  ingress:
    env_file:
      - ingress/.env
    container_name: ingress
    build:
      context: .
      dockerfile: ingress/Dockerfile
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    depends_on:
      - frontend
    volumes:
      - ./ingress:/app
